security:
    providers:
        users_in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            stateless: true
            provider: users_in_memory
            custom_authenticators:
                - App\Infrastructure\Security\ApiKeyAuthenticator

    access_control:
        - { path: ^/api, roles: ROLE_API_CLIENT }
